import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import Navbar from "./_Components/Navbar/Navbar";
import Footer from "./_Components/Footer";
import { Toaster } from "react-hot-toast";
import Providers from "./_Components/Providers"
import WishlistInitializer from "./_Components/WishlistInitializer";
import CartInitializer from "./_Components/CartInitializer";

const exo = Exo({
  subsets: ["latin"],
  variable: "--font-exo",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={exo.className}>
        <Providers>
          <CartInitializer />
          <WishlistInitializer />
          <Toaster position="top-right"/>
          <div className="min-h-screen bg-stone-200">          
            <Navbar/>
            {children}
            <Footer/>
          </div>
        </Providers>
      </body>
    </html>
  )
}
